name: Notify

on:
  schedule:
    - cron: "0 21 * * *"
  # 動作確認用に push 時も実行させる
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: "ubuntu-latest"
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
    steps:
      - uses: "actions/checkout@v4"

      - id: "setup-node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 18.x

      - id: "install"
        run: yarn install --frozen-lockfile

      - id: "notify-ramdomly"
        run: yarn ts-node src/notifyRandomly.ts

      - id: "notify-yesterday-tweets"
        run: yarn ts-node src/notifyYesterdayTweets.ts
